# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTemplate

  target 'ReactNativeTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
